=== yeshwant-singh-zz/jenkins_plugin_test/src/main/resources/DOMElements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="elements" type="elementsType"/>
    <xs:complexType name="elementsType">
        <xs:sequence>
            <xs:element type="elementType" name="element" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="elementType">
        <xs:sequence>
            <xs:element name="xpath" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="id" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="css" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="class" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="tag" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="partialLinkText" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="linkText" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="name" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:minLength value="3"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== yeshwant-singh-zz/jenkins_plugin_test/src/main/java/com/PriceScraper/PriceScraperDomElements.xml
<?xml version="1.0"?>
<elements xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../../../resources/DOMElements.xsd">
    <element name="aSearchBar">
        <id>twotabsearchtextbox</id>
    </element>

    <element name="aSearchKey">
        <xpath>//input[@value='Go']</xpath>
    </element>

    <element name="aSmartphones">
        <xpath>//li[@style='margin-left: 34px']/a</xpath>
        <!--<name>Smartphones</name>-->
        <!--<xpath>//a[@href='/s/ref=sr_nr_n_1?fst=as%3Aoff&amp;rh=n%3A976419031%2Cn%3A1389401031%2Cn%3A1805560031%2Ck%3Aiphone&amp;keywords=iphone&amp;ie=UTF8&amp;qid=1462461431&amp;rnid=976420031']</xpath>-->
    </element>

    <element name="aPrices">
        <class>s-price</class>
    </element>

    <element name="fSearchBar">
        <class>LM6RPg</class>
    </element>

    <element name="fSearchKey">
        <class>vh79eN</class>
    </element>

    <element name="fSmartphones">
        <xpath>//a[@path='mobiles']</xpath>
    </element>

    <element name="fPrices">
        <class>fk-font-17</class>
    </element>

</elements>
